image: quay.io/vgteam/dind

before_script:
  - whoami
  - sudo apt-get -q -y update
  # Cactus dependencies from Dockerfile (todo: centralize)
  - sudo apt-get -q -y git gcc g++ build-essential python3 python3-dev zlib1g-dev wget valgrind libbz2-dev libhiredis-dev pkg-config libhdf5-dev liblzo2-dev libtokyocabinet-dev
  # Make sure we have some curl stuff for pycurl which we need for some Python stuff
  - sudo apt-get -q -y install docker.io python-virtualenv libcurl4-gnutls-dev libgnutls28-dev
  - startdocker || true
  - docker info

after_script:
  - stopdocker || true
  
stages:
  - test

test-job:
  stage: test
  script:
    - virtualenv -p python3.6 venv
    - source venv/bin/activate
    - pip install toil==3.24.0
    - pip install -U .
    - make -j 4 evolver_test
  artifacts:
    # Let Gitlab see the junit report
    reports:
      junit: test-report.xml
    when: always
  
